site_name: Testkube
site_description: "Your Kubernetes Testing Friend"
site_author: "Kubeshop testkube Team"
docs_dir: docs/
repo_name: "kubeshop/testkube"
repo_url: "https://github.com/kubeshop/testkube"
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.expand

extra_css:
  - css/extra.css

nav:
  - Welcome: index.md
  - Installation: installing.md
  - Getting Started: getting-started.md
  - Using Testkube:
      - UI: UI.md
      - Test Suites:
          - Creating: testsuites-creating.md
          - Running: testsuites-running.md
          - Getting results: testsuites-getting-results.md
      - Tests:
          - Creating: tests-creating.md
          - Adding Test Variables: tests-variables.md
          - Running: tests-running.md
          - Getting Results: tests-getting-results.md
      - Scheduling: scheduling.md
      - Artifact Storage: artifacts-storage.md
      - Metrics: metrics.md
  - Test Types:
      - Cypress: executor-cypress.md
      - Postman: executor-postman.md
      - SoapUI: executor-soapui.md
      - K6: executor-k6.md
      - SoapUI Tests: executor-soapui.md
      - KubePug Tests: executor-kubepug.md
      - Artillery.io: executor-artillery.md
      - Maven: executor-maven.md
      - Gradle: executor-gradle.md
      - Curl: executor-curl.md
      - Creating New Test Types: executor-custom.md
  - CLI Reference:
      - Overview: cli/kubectl-testkube.md
      - Abort Command: cli/kubectl-testkube_abort.md
      - Completion Command: cli/kubectl-testkube_completion.md
      - Config Command: cli/kubectl-testkube_config.md
      - Create Command: cli/kubectl-testkube_create.md
      - Dashboard Command: cli/kubectl-testkube_dashboard.md
      - Delete Command: cli/kubectl-testkube_delete.md
      - Disable Command: cli/kubectl-testkube_disable.md
      - Download Command: cli/kubectl-testkube_download.md
      - Enable Command: cli/kubectl-testkube_enable.md
      - Generate Command: cli/kubectl-testkube_generate.md
      - Get Command: cli/kubectl-testkube_get.md
      - Install Command: cli/kubectl-testkube_install.md
      - Migrate Command: cli/kubectl-testkube_migrate.md
      - Run Command: cli/kubectl-testkube_run.md
      - Migrate Command: cli/kubectl-testkube_migrate.md
      - Status Command: cli/kubectl-testkube_status.md
      - Update Command: cli/kubectl-testkube_update.md
      - Upgrade Command: cli/kubectl-testkube_upgrade.md
      - Version Command: cli/kubectl-testkube_version.md
      - Watch Command: cli/kubectl-testkube_watch.md
  - OpenAPI Definition: openapi.md
  - Integrations:
      - Integrating with CI/CD: testkube-automation.md
      - Integrating with Slack: slack-integration.md
  - Authentication:
      - OAuth for UI: oauth-ui.md
      - OAuth for CLI: oauth-cli.md
  - Contributing:
      - Contributing: contributing.md
      - Development:
          - Local Runs: development.md
          - Custom Resources: development-crds.md
  - Architecture: architecture.md
  - Telemetry: telemetry.md

extra:
  analytics:
    provider: google
    property: UA-204665550-6

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - render_swagger
  - search

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

copyright: Copyright &copy; 2022 <a href="https://kubeshop.io">Kubeshop</a>
