site_name: Testkube
site_description: "Your Kubernetes Testing Friend"
site_author: "Kubeshop testkube Team"
docs_dir: docs/
repo_name: "kubeshop/testkube"
repo_url: "https://github.com/kubeshop/testkube"
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.expand

extra_css:
  - css/extra.css

nav:
  - Welcome: index.md
  - Installation: installing.md
  - Getting Started: getting-started.md
  - Managing Test Suites:
      - Creating: testsuites-creating.md
      - Running: testsuites-running.md
      - Getting results: testsuites-getting-results.md
  - Managing Tests:
      - Creating: tests-creating.md
      - Running: tests-running.md
      - Getting results: tests-getting-results.md
      - Postman Collections: executor-postman.md
      - Cypress Tests: executor-cypress.md
      - Curl Commands: executor-curl.md
  - Executors:
      - Creating custom executor: executor-custom.md
  - CLI Reference:
      - Overview: cli/testkube.md
      - Install Cmd: cli/testkube_install.md
      - TestSuites Cmd: cli/testkube_testsuites.md
      - Tests Cmd: cli/testkube_tests.md
      - Dashboard Cmd: cli/testkube_dashboard.md
  - Integrating with CI/CD: testkube-automation.md
  - Dashboard: dashboard.md
  - Metrics: metrics.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Development: development.md
  - OpenAPI Definition: openapi.md
  - Telemetry: telemetry.md
  - Storage: artifacts-storage.md

extra:
  analytics:
    provider: google
    property: UA-204665550-6

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# plugins:
# - render_swagger

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

copyright: Copyright &copy; 2022 <a href="https://kubeshop.io">Kubeshop</a>
