apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-webserver
  labels:
    app: debug-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-webserver
  template:
    metadata:
      labels:
        app: debug-webserver
    spec:
      containers:
        - name: debug-webserver
          image: ex00/debug-webserver:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: debug
spec:
  selector:
    app: debug-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
