apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: zap-executor
  namespace: testkube
spec:
  executor_type: job
  image: vlia/testkube-zap-executor:0.0.1
  types:
    - zap/api
    - zap/baseline
    - zap/full
  features:
    - artifacts
