openapi: 3.0.1

servers:
  - url: https://api.testkube.io
    description: "Testkube Cloud API"

info:
  title: Testkube Cloud API
  description: "API for Testkube Cloud"
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: local

externalDocs:
  description: "Find out more about Testkube"
  url: https://cloud.kubeshop.io/

tags:
  - name: executor

paths:
  /executors:
    get:
      tags:
        - executor
      summary: "List executors"
      description: "List executors available in cluster"
      operationId: listExecutors
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Executor"
            text/yaml:
              schema:
                type: string
        "502":
          description: "problem with read information from kubernetes cluster"
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Problem"

components:
  schemas:
    Executor:
      description: CRD based executor data
      type: object
      properties:
        executorType:
          description:
            ExecutorType one of "rest" for rest openapi based executors
            or "job" which will be default runners for testkube soon
          type: string
        image:
          description: Image for kube-job
          type: string
        imagePullSecrets:
          type: array
          description: "container image pull secrets"
          items:
            $ref: "#/components/schemas/LocalObjectReference"
        command:
          type: array
          description: "container executor image command"
          items:
            type: string
          example:
            - "curl"
        args:
          type: array
          description: "additional executor binary arguments"
          items:
            type: string
          example:
            - "--repeats"
            - "5"
            - "--insecure"
        types:
          description: Types defines what types can be handled by executor e.g.
            "postman/collection", ":curl/command" etc
          items:
            type: string
          type: array
        uri:
          description: URI for rest based executors
          type: string
        contentTypes:
          description: list of handled content types
          items:
            type: string
          type: array
        jobTemplate:
          description: Job template to launch executor
          type: string
        labels:
          type: object
          description: "executor labels"
          additionalProperties:
            type: string
          example:
            env: "prod"
            app: "backend"
        features:
          description: Available executor features
          type: array
          items:
            type: string
            enum:
              - artifacts
              - junit-report
        meta:
          $ref: "#/components/schemas/ExecutorMeta"

    LocalObjectReference:
      description: Reference to Kubernetes object
      type: object
      properties:
        name:
          type: string

    ExecutorMeta:
      description: Executor meta data
      type: object
      properties:
        iconURI:
          description: URI for executor icon
          type: string
          example: /assets/k6.jpg
        docsURI:
          description: URI for executor docs
          type: string
          example: https://kubeshop.github.io/testkube/test-types/executor-k6
        tooltips:
          type: object
          description: executor tooltips
          additionalProperties:
            type: string
          example:
            general: "please provide k6 test script for execution"

    Problem:
      description: problem response in case of error
      type: object
      properties:
        type:
          type: string
          description: Type contains a URI that identifies the problem type.
          example: https://kubeshop.io/testkube/problems/invalidtestname
        title:
          type: string
          description: Title is a short, human-readable summary of the problem type. This title SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
          example: Invalid test name
        status:
          type: integer
          description: HTTP status code for this occurrence of the problem.
          example: 500
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: Your test name can't contain forbidden characters like "}}}" passed
        instance:
          type: string
          description: A URI that identifies the specific occurrence of the problem. This URI may or may not yield further information if de-referenced.
          example: http://10.23.23.123:8088/tests
