env:
  # Goreleaser always uses the docker buildx builder with name "default"; see
  # https://github.com/goreleaser/goreleaser/pull/3199
  # To use a builder other than "default", set this variable.
  # Necessary for, e.g., GitHub actions cache integration.
  - DOCKER_BUILDX_BUILDER={{ if index .Env "DOCKER_BUILDX_BUILDER"  }}{{ .Env.DOCKER_BUILDX_BUILDER }}{{ else }}default{{ end }}
  # Setup to enable Docker to use, e.g., the GitHub actions cache; see
  # https://docs.docker.com/build/building/cache/backends/
  # https://github.com/moby/buildkit#export-cache
  - DOCKER_BUILDX_CACHE_FROM={{ if index .Env "DOCKER_BUILDX_CACHE_FROM"  }}{{ .Env.DOCKER_BUILDX_CACHE_FROM }}{{ else }}type=registry{{ end }}
  - DOCKER_BUILDX_CACHE_TO={{ if index .Env "DOCKER_BUILDX_CACHE_TO"  }}{{ .Env.DOCKER_BUILDX_CACHE_TO }}{{ else }}type=inline{{ end }}

builds:
  - id: "linux"
    main: "./contrib/executor/jmeter/cmd/agent"
    binary: "jmeter"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/jmeter/build/agent/Dockerfile"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-jmeter-executor:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
    extra_files:
      - ./contrib/executor/jmeter/lib/jmeter-plugins-cmn-jmeter-0.6.jar
      - ./contrib/executor/jmeter/plugins/jmeter-plugins-functions-2.1.jar
      - ./contrib/executor/jmeter/plugins/jmeter-plugins-manager-1.3.jar
      - ./contrib/executor/jmeter/scripts/entrypoint.sh

  - dockerfile: "./contrib/executor/jmeter/build/agent/Dockerfile"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-jmeter-executor:{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
    extra_files:
      - ./contrib/executor/jmeter/lib/jmeter-plugins-cmn-jmeter-0.6.jar
      - ./contrib/executor/jmeter/plugins/jmeter-plugins-functions-2.1.jar
      - ./contrib/executor/jmeter/plugins/jmeter-plugins-manager-1.3.jar
      - ./contrib/executor/jmeter/scripts/entrypoint.sh

docker_manifests:
  - name_template: kubeshop/testkube-jmeter-executor:{{ .Version }}
    image_templates:
      - kubeshop/testkube-jmeter-executor:{{ .Version }}-amd64
      - kubeshop/testkube-jmeter-executor:{{ .Version }}-arm64v8
  - name_template: kubeshop/testkube-jmeter-executor:latest
    image_templates:
      - kubeshop/testkube-jmeter-executor:{{ .Version }}-amd64
      - kubeshop/testkube-jmeter-executor:{{ .Version }}-arm64v8

release:
  disable: true
