env:
  # Goreleaser always uses the docker buildx builder with name "default"; see
  # https://github.com/goreleaser/goreleaser/pull/3199
  # To use a builder other than "default", set this variable.
  # Necessary for, e.g., GitHub actions cache integration.
  - DOCKER_BUILDX_BUILDER={{ if index .Env "DOCKER_BUILDX_BUILDER"  }}{{ .Env.DOCKER_BUILDX_BUILDER }}{{ else }}default{{ end }}
  # Setup to enable Docker to use, e.g., the GitHub actions cache; see
  # https://docs.docker.com/build/building/cache/backends/
  # https://github.com/moby/buildkit#export-cache
  - DOCKER_BUILDX_CACHE_FROM={{ if index .Env "DOCKER_BUILDX_CACHE_FROM"  }}{{ .Env.DOCKER_BUILDX_CACHE_FROM }}{{ else }}type=registry{{ end }}
  - DOCKER_BUILDX_CACHE_TO={{ if index .Env "DOCKER_BUILDX_CACHE_TO"  }}{{ .Env.DOCKER_BUILDX_CACHE_TO }}{{ else }}type=inline{{ end }}

builds:
  - id: "linux"
    main: "./contrib/executor/playwright/cmd/agent"
    binary: "playwright"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/playwright/build/agent/Dockerfile.pnpm"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/playwright/build/agent/Dockerfile.pnpm"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/playwright/build/agent/Dockerfile.npm"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-playwright-executor:{{ .Version }}-npm-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/playwright/build/agent/Dockerfile.npm"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-playwright-executor:{{ .Version }}-npm-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/playwright/build/agent/Dockerfile.yarn"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-playwright-executor:{{ .Version }}-yarn-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/playwright/build/agent/Dockerfile.yarn"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-playwright-executor:{{ .Version }}-yarn-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

docker_manifests:
  - name_template: kubeshop/testkube-playwright-executor:{{ .Version }}-npm
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:npm
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:pnpm
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-pnpm-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:{{ .Version }}-yarn
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-yarn-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-yarn-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:yarn
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-yarn-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-yarn-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:latest
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-arm64v8
  - name_template: kubeshop/testkube-playwright-executor:{{ .Version }}
    image_templates:
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-amd64
      - kubeshop/testkube-playwright-executor:{{ .Version }}-npm-arm64v8

release:
  disable: true

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - 'sign'
      - '${artifact}'
      - "--yes"