name: Docker images

on:
  push:
    tags: 
      # - "v[0-9]+.[0-9]+.[0-9]+"
      # - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "vTesting[0-9]+.[0-9]+.[0-9]+"
      - "vTesting[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  releasing_helm_chart_api_server:
    runs-on: ubuntu-latest
    steps:
      - name: getting Tag name pushed.
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Editing helm-release repo with version based on a Tag pushed.
        run: |
          git clone https://fog1985:$HELM_CHARTS_UPDATE@github.com/kubeshop/helm-charts

          cd helm-charts
          git config user.name "ci/cd-github-bot"
          git config user.email "github-bot@kubeshop.io"
          
          # Getting api-server chart version based on the pushed TAG:
          version_full=$(echo $RELEASE_VERSION | sed 's/^v//')
          echo "Version recieved: $version_full"

          # Getting TestKube main chart version:
          tk_version_full=

          # Bumping TestKube version by one:
          # tk_version_major=$(echo $tk_version_full | awk -F\. '{print $1}')
          # tk_version_minor=$(echo $tk_version_full | awk -F\. '{print $2}')
          # tk_version_patch=$(echo $tk_version_full | awk -F\. '{print $3}')

          # Incrementing testKube helm charts patch version by one:
          tk_version_patch=$(expr $tk_version_patch + 1)

          # New TestKube full version:
          tk_version_full_bumped=$tk_version_major.$tk_version_minor.$tk_version_patch
          echo "New version is: $tk_version_full_bumped"

          # Editing api-server Chart, and App versions:
          sed -i "s/^version: .*$/version: $version_full/" ./charts/api-server/Chart.yaml
          sed -i "s/^appVersion: .*$/appVersion: $version_full/" ./charts/api-server/Chart.yaml
          echo -e "\nChecking changes made to Chart.yaml of api-server\n"
          cat ./charts/api-server/Chart.yaml

          # Editing Docker tag image for api-server:
          sed -i "s/tag:.*$/tag: \"$version_full\"/" ./charts/api-server/values.yaml
          echo -e "\nChecking changes made to Docker image:\n"
          grep -i "tag" ./charts/api-server/values.yaml

          # Editing TestKube's main chart version:
          sed -i "s/^version:.*/version: $tk_version_full_bumped/" ./charts/testkube/Chart.yam
          echo -e "\nChecking if testkube's main Chart.yaml version has been updated:\n"
          grep -iE -A 1 "^version" ./charts/testkube/Chart.yaml

          # Editing TestKube dependency Chart.yaml for api-server:
          sed -i "/name: api-server/{n;s/^.*version.*/  version: $version_full/}" ./charts/testkube/Chart.yaml
          echo -e "\nChecking if testkube's Chart.yaml dependencie has been updated:\n"
          grep -iE -A 1 "name: api-server" ./charts/testkube/Chart.yaml

          # # Commiting and pushing changes:
          # git add -A
          # git commit -m "Tag: $version_full; Api-server CI/CD. Bumped helm chart, app and docker image tag versions."

          # git remote -v

          # # git push origin main
          # git push --set-upstream https://fog1985:$HELM_CHARTS_UPDATE@github.com/kubeshop/helm-charts main

        env:
          HELM_CHARTS_UPDATE: ${{ secrets.HELM_CHARTS_UPDATE }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}