name: Docker images
on:
  push:
    branches:
      - main
      - 1352-build-arm-image

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag version
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          docker buildx ls

      - name: Docker meta for API Server
        id: meta_api_server
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-api-server
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: build/api-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_api_server.outputs.tags }}
          build-args: |
            TOKEN=${{ secrets.CI_BOT_TOKEN }}
            VERSION=${{ steps.vars.outputs.tag }}
            COMMIT=${{ github.sha }}
            ANALYTICS_TRACKING_ID=${{secrets.TESTKUBE_API_GA_MEASUREMENT_ID}}
            ANALYTICS_API_KEY=${{secrets.TESTKUBE_API_GA_MEASUREMENT_SECRET}}

      - name: Inspect
        run: docker manifest inspect !$


#      - name: Step
#        id: github_sha
#        run: echo "::set-output name=sha_short::${GITHUB_SHA::7}"
#
#      - name: Build API Server
#        uses: docker/bake-action@v1
#        with:
#          files: |
#            build/api-server/docker-bake.hcl
#            ${{ steps.meta_api_server.outputs.bake-file }}
#          targets: build
#          set: |
#            build.args.TOKEN=${{ secrets.CI_BOT_TOKEN }}
#            build.args.VERSION=${{ steps.vars.outputs.tag }}
#            build.args.COMMIT=${{ github.sha }}
#            build.args.ANALYTICS_TRACKING_ID=${{secrets.TESTKUBE_API_GA_MEASUREMENT_ID}}
#            build.args.ANALYTICS_API_KEY=${{secrets.TESTKUBE_API_GA_MEASUREMENT_SECRET}}
#          push: true

#      #Trigger Helm repo workflow to deploy API to Stage cluster
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.CI_BOT_TOKEN }}
#          repository: kubeshop/helm-charts
#          event-type: trigger-workflow
#          client-payload: '{"image_tag": "sha-${{ steps.github_sha.outputs.sha_short }}"}'
