name: Helm releaser for executor
on:
  repository_dispatch:
    types: [ trigger-executor-helm-releaser ]

jobs:
  releasing_helm_chart_executor:
    runs-on: ubuntu-latest
    steps:
      - name: Editing helm-release repo with version based on a Tag pushed.
        run: |

          # Setting up Git:

          git clone https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts
          cd ./helm-charts
          git config user.name "kubeshop-bot"
          git config user.email "kubeshop-bot@kubeshop.io"

          git fetch origin "release-$RELEASE_VERSION"
          git checkout "release-$RELEASE_VERSION"

          # Calling chart releaser script by passing needed folder name:
          # E.G. in order to relase api-server": 
          # -->> ./chart_releaser.sh --helm-chart-folder api-server

          export GH_PUSH_TOKEN
          export RELEASE_VERSION

          cd ./scripts
          executors="artillery curl cypress ginkgo gradle init jmeter k6 kubepug maven playwright postman scraper soapui"
          for executor in $executors
          do
            ./chart_releaser.sh --testkube-executor-name ${executor} --main-chart false --branch true
          done

          git checkout main
          git merge "release-$RELEASE_VERSION"
          # git push origin main
          git push --set-upstream https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts main
        env:
          GH_PUSH_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          RELEASE_VERSION: ${{ github.event.client_payload.release_version }}