name: "Linting"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Linting GO code
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable revive
          only-new-issues: true