name: "Linting"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    
permissions:
  contents: read
  pull-requests: read

jobs:
  prlint:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  golangci:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Linting GO code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --enable revive --timeout=5m
          only-new-issues: true
