name: Code build and checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Unit test
      run: go test -v ./...

    # Don't work yet as expected https://github.com/nwestfall/openapi-action/issues/3
    - name: OpenAPI Lint Checks
      uses: nwestfall/openapi-action@v1.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        file: api/v1/testkube.yaml