name: Code build and checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Unit test
      run: go test -v ./...

    # Don't work exits with error 
    # No ruleset has been found. Please provide a ruleset using the --ruleset CLI argument, or make sure your ruleset file matches .?spectral.(js|ya?ml|json)
    # - name: openapi-check
    #   uses: vaibhav-jain/spectral-action/@v2.6
    #   with:
    #     file_path: api/testkube.yaml

    - name: OpenAPI Lint Checks
      uses: nwestfall/openapi-action@v1.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        file: api/v1/testkube.yaml