name: Code build and checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: bitnami/mongodb
        ports:
          - 27017:27017
      nats:
        image: bitnami/nats
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222
      minio:
        image: bitnami/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minio99
          MINIO_ROOT_PASSWORD: minio123


    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Unit test
        run: gotestsum --format short-verbose --junitfile unit-tests.xml --jsonfile unit-tests.json ./...

      - name: Unit Test Summary
        if: always()
        uses: test-summary/action@v1
        with:
          paths: |
            unit-tests.xml

      - name: Annotate unit tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: unit-tests.json

      - name: Integration tests
        run: |
          sudo apt-get install -y git
          gotestsum --format short-verbose --junitfile integration-tests.xml --jsonfile integration-tests.json -- -tags=integration ./...

      - name: Integration Test Summary
        if: always()
        uses: test-summary/action@v1
        with:
          paths: |
            integration-tests.xml

      - name: Annotate integration tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: integration-tests.json

      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: api/v1/testkube.yaml
